version: '3'

services:
   cassandra:
     image: cassandra
     restart: always
     ports:
       - 9042:9042
   mysql:
     image: mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: pw
